sudo: false
language: ruby
ruby:
- 2.2

script: bundle exec jekyll build --safe && bundle exec htmlproof --checks-to-ignore ScriptCheck ./_site

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true 
