sudo: false
language: ruby
ruby:
- 2.2

install: gem install jekyll html-proofer --no-ri --no-rdoc
script: jekyll build && htmlproof --checks-to-ignore ScriptCheck ./_site

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true 
