sudo: false
language: ruby
rvm:
- 2.3.3

script: bundle exec jekyll build --safe && bundle exec htmlproofer --checks-to-ignore ScriptCheck ./_site

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true 
